### ISSUE TITLE
chroma/luma/transparent

### ISSUE THREAD

**Issue by robinmordasiewicz** [iamjohnbarker/h2r-graphics-releases#1]
I would like to be able to run the H2R graphics with a transparent background. I share a mirrored desktop to my ATEM and I would like to overlay H2R graphics over my screen with a transparent background rather than a chroma or black background which is normally used for chroma or luma key.

**Comment by ChristopherKossatz** [comment]
HDMI can't send alpha values, so this isn't possible. This has nothing to do with H2R graphics or the Atem mini but rather with the HDMI protocol itself.

**Comment by robinmordasiewicz** [comment]
I’m looking for H2R to play as a transparent window on a desktop application so that applications below H2R can still be visible.

—
Robin Mordasiewicz
________________________________
