### ISSUE TITLE
Break autoplay stuck

### ISSUE THREAD

**Issue by gjaekel** [iamjohnbarker/h2r-graphics-releases#17]
Maybe it's just because the sheet is not as expected, but today I used the break feature the first time for a conference and I become stuck "in the middle" and I have to switch to manual mode.

Is there any documentation? May I provide the sheet ID?

**Comment by gjaekel** [comment]
I just found the problem: I must have copied the date column at some row in the middle by accident by dragging the "cross" because it was auto-incremented to the next day at this position.

This was the row where it seems to got stuck, because it was scheduled for the next day.

**Comment by iamjohnbarker** [comment]
Good to have you back on track!

**Comment by gjaekel** [comment]
The provided schedule provided by your tool -- with other words: your work --  got the appreciation of the referents and the participants of this small conference.
