### ISSUE TITLE
v2.14.3 beta or stable?

### ISSUE THREAD

**Issue by core-code** [iamjohnbarker/h2r-graphics-releases#25]
v2.14.3 is clearly marked as both BETA and PRERELEASE in the github release page, yet it is linked as the latest official version on the download page ( https://h2r.graphics/download/ ).

what is it - beta/prerelease or official/latest?

thanks!

**Comment by iamjohnbarker** [comment]
Hey!

2.14.3 is indeed the latest release - Not sure why it's showing as a BETA or Pre-release on GitHub, I think I fixed that now!

**Comment by core-code** [comment]
yes, it is fixed
