### ISSUE TITLE
Publish source code / Linux version

### ISSUE THREAD

**Issue by hansegucker** [iamjohnbarker/h2r-graphics-releases#4]
I like this application and it's way to simplify the things very much. Thank you for a lot of good work!

I usually work on Linux systems and use them for everything. As I guess, your system is built on the basis of Electron and NodeJS, so it should be an option to publish a Linux version (e. g. for Debian based systems as deb package or as an executable to use on multiple systems). I understand that's a lot of extra work, so that I suggest publishing the source code on GitHub.

I would be very glad to get an answer!

**Comment by MarcusAlzona** [comment]
FYI it seems that a Linux AppImage was released in October 2020 for version 0.32 - does that fulfill the goal of this issue @hansegucker?  If so, I think this could be resolved.  Or was it you really thought the source should be on GitHub?

Also, I opened a separate ticket for a Raspberry Pi release as well - so not an x86 AppImage, but an ARM one.  See Issue #13 - [Raspberry Pi (ARM-Linux) H2R Graphics Release](13)

**Comment by hansegucker** [comment]
Oh, thanks for the information, @MarcusAlzona. I have not taken a look at the downloads page for a long time, but I'm very glad that there is a Linux version now. Of course, publishing the source code under a free license would be even better, but you can't have everything :wink:
